apiVersion: v1
kind: Service
metadata:
  name: rap-analyzer-service
  namespace: default
  labels:
    app: rap-analyzer
spec:
  type: ClusterIP
  selector:
    app: rap-analyzer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
